# SPDX-FileCopyrightText: 2025, 2026 yonasBSD
#
# SPDX-License-Identifier: MIT
---
exclude_paths:
  - "backpack/cli/**"
  - "backpack/e2e/**"
  - "xtask/**"
  - "**/tests/**"
  - "benches/**"
  - "utils/**"
  - ".github/**"
  - ".gitignore"
  - "**/*.lock"
  - "**/*.toml"
  - "**/*.md"
  - "*.md"
  - "LICENSE"
